'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => 't'+crypto.randomUUID().replaceAll('-','');
const safeUrl = value => {try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const color = (v,fallback='#293a38') => /^#[0-9a-f]{6}$/i.test(v)?v:fallback;
const key='talk-excerpt-v1';
let state={version:1,id:uid(),title:'어느 오후의 대화',url:'',people:[{id:uid(),name:'서연',side:'left',photo:'',text:'#34423c',nick:'#54725b',bubble:'#ffffff'},{id:uid(),name:'도윤',side:'right',photo:'',text:'#34423c',nick:'#54725b',bubble:'#e1ebcf'}],blocks:[]};
const makeMessage=(person,text)=>({id:uid(),type:'message',person,text,time:'',reply:null,links:[]});
state.blocks=[makeMessage(state.people[0].id,'우리 이 대화, 오래 기억해 두자.'),{id:uid(),type:'fold',label:'··· 중략 ··· 펼치기',children:[makeMessage(state.people[1].id,'작은 이야기들도 전부 담아둘게.')]},makeMessage(state.people[1].id,'좋아. 여기서부터 다시 이어가자.')];
function messages(){return state.blocks.flatMap(b=>b.type==='fold'?b.children:[b]);}
function validate(s){
 if(!s||s.version!==1||!Array.isArray(s.people)||!s.people.length||!Array.isArray(s.blocks)||typeof s.title!=='string'||typeof s.url!=='string')throw Error('지원하지 않는 프로젝트 형식입니다.');
 const ids=new Set();const validId=id=>{if(typeof id!=='string'||!/^t[a-zA-Z0-9-]+$/.test(id)||ids.has(id))throw Error('고유 ID가 올바르지 않습니다.');ids.add(id);};validId(s.id);
 for(const p of s.people){validId(p.id);if(typeof p.name!=='string'||!['left','right'].includes(p.side)||typeof p.photo!=='string')throw Error('인물 설정을 확인하세요.');}
 const all=[];for(const b of s.blocks){if(b.type==='fold'){validId(b.id);if(typeof b.label!=='string'||!Array.isArray(b.children)||!b.children.length)throw Error('접기 구간이 잘못되었습니다.');all.push(...b.children);}else all.push(b);}
 for(const m of all){validId(m.id);if(m.type!=='message'||typeof m.text!=='string'||!s.people.some(p=>p.id===m.person)||!Array.isArray(m.links))throw Error('대화 데이터가 잘못되었습니다.');for(const l of m.links)if(typeof l.label!=='string'||!safeUrl(l.url))throw Error('답장 링크가 잘못되었습니다.');if(m.reply&&(!['local','external'].includes(m.reply.kind)||(m.reply.kind==='external'&&!safeUrl(m.reply.url))))throw Error('원문 링크가 잘못되었습니다.');}
 for(const m of all)if(m.reply?.kind==='local'&&(!all.some(x=>x.id===m.reply.id)||m.reply.id===m.id))throw Error('답장의 원본을 찾을 수 없습니다.');return s;
}
let initialNotice='';try{const saved=localStorage.getItem(key);if(saved)state=validate(JSON.parse(saved));}catch{initialNotice='자동 저장을 불러오지 못했습니다. 프로젝트 파일로 복원할 수 있어요.';}
let activePerson=state.people[0].id,editing=null,insertion=null,history=[],selected=new Set();
function notice(t){$('status').textContent=t;}
function checkpoint(){history.push(JSON.stringify(state));if(history.length>50)history.shift();}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));}catch{notice('자동 저장 공간이 부족합니다. 프로젝트 저장 버튼으로 파일을 보관하세요.');}}
function commit(){persist();render();}
function person(id){return state.people.find(p=>p.id===id);}
function avatar(p){return safeUrl(p.photo)?`<img class="avatar" src="${esc(safeUrl(p.photo))}" alt="">`:`<span class="avatar">${esc(p.name.slice(0,1))}</span>`;}
function renderPeople(){const q=$('person-search').value.toLowerCase();$('people').innerHTML=state.people.filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<button class="person ${p.id===activePerson?'active':''}" data-person="${p.id}">${avatar(p)}<span>${esc(p.name)} <small>${p.side==='left'?'왼쪽':'오른쪽'}</small></span></button>`).join('');const p=person(activePerson)||state.people[0];activePerson=p.id;$('person-form').innerHTML=`<label>닉네임<input name="name" value="${esc(p.name)}" required></label><label>대화 위치<select name="side"><option value="left" ${p.side==='left'?'selected':''}>왼쪽</option><option value="right" ${p.side==='right'?'selected':''}>오른쪽</option></select></label><label>프사 이미지 주소<input name="photo" type="url" value="${esc(p.photo)}" placeholder="https://…"></label><p class="hint">티스토리 등에 올린 이미지 주소를 입력하세요.</p><div class="swatches">${[['nick','닉네임색'],['text','글자색'],['bubble','말풍선색']].map(([k,n])=>`<label>${n}<input name="${k}" type="color" value="${color(p[k])}"></label>`).join('')}</div><button type="submit">인물 설정 적용</button> <button type="button" id="remove-person">삭제</button>`;}
function row(m){return `<article class="message-row"><div class="row-head"><input type="checkbox" aria-label="대화 선택" data-select="${m.id}" ${selected.has(m.id)?'checked':''}><strong>${esc(person(m.person).name)}</strong><small>${esc([m.date,m.time].filter(Boolean).join(' '))}</small>${m.reply?'<small>↳ 답장</small>':''}</div><p>${esc(m.text)}</p><div class="row-actions">${[['edit','수정'],['insert','아래 끼워넣기'],['up','↑'],['down','↓'],['link','링크 복사'],['delete','삭제']].map(([a,n])=>`<button data-action="${a}" data-id="${m.id}">${n}</button>`).join('')}</div></article>`;}
function render(){renderPeople();$('title').value=state.title;$('post-url').value=state.url;$('undo').disabled=!history.length;$('messages').innerHTML=state.blocks.map(b=>b.type==='fold'?`<section class="fold-row"><div><input aria-label="접기 문구" data-fold-label="${b.id}" value="${esc(b.label)}"><button data-action="unfold" data-id="${b.id}">묶음 해제</button></div>${b.children.map(row).join('')}</section>`:row(b)).join('');$('preview').innerHTML=output(false);}
function targetId(id){return state.blocks.find(b=>b.type==='fold'&&b.children.some(m=>m.id===id))?.id||id;}
function output(exporting=true){
 const prefix=exporting?'':'preview-';
 const bubble=m=>{const p=person(m.person),right=p.side==='right';let quote='';if(m.reply){const original=m.reply.kind==='local'?messages().find(x=>x.id===m.reply.id):null;const name=original?person(original.person).name:m.reply.name;const text=original?original.text:m.reply.text;const href=original?'#'+prefix+targetId(original.id):safeUrl(m.reply.url);quote=`<a href="${esc(href)}" style="display:block;border-left:3px solid #96aa81;padding:5px 9px;margin-bottom:8px;color:inherit;text-decoration:none;font-size:12px"><b>${esc(name)}</b><br>${esc((text||'').slice(0,120))}${original&&targetId(original.id)!==original.id?'<br><small>접힌 구간으로 이동 · 펼쳐서 확인</small>':''}</a>`;}
 return `${m.date?`<div style="text-align:center;font-size:11px;color:#788574;margin:15px 0 5px">${esc(m.date)}</div>`:''}<div id="${prefix+m.id}" style="display:flex;flex-direction:${right?'row-reverse':'row'};gap:9px;margin:17px 0;scroll-margin-top:24px"><div style="flex:none;width:34px;height:34px;border-radius:50%;background:#dbe5d2;overflow:hidden;text-align:center;line-height:34px">${safeUrl(p.photo)?`<img src="${esc(safeUrl(p.photo))}" alt="" style="width:100%;height:100%;object-fit:cover">`:esc(p.name.slice(0,1))}</div><div style="max-width:78%;min-width:0;text-align:${right?'right':'left'}"><div style="color:${color(p.nick)};font-size:12px;margin-bottom:5px">${esc(p.name)}</div><div style="text-align:left;background:${color(p.bubble,'#ffffff')};color:${color(p.text)};border-radius:12px;padding:12px 14px;overflow-wrap:anywhere;line-height:1.7">${quote}<div style="white-space:pre-wrap">${esc(m.text)}</div></div><small style="color:#7c887c;font-size:10px">${esc(m.time)}</small>${m.links.map(l=>`<a href="${esc(safeUrl(l.url))}" style="display:block;font-size:11px;color:#4d7044;margin-top:5px">↗ ${esc(l.label)}</a>`).join('')}</div></div>`;};
 return `<div id="${prefix+state.id}" lang="ko" style="max-width:720px;margin:16px auto;padding:22px;background:#eff2ec;border-radius:12px;font-family:system-ui,sans-serif;color:#34423c;box-sizing:border-box"><div style="font-size:16px;font-weight:bold;padding-bottom:12px;border-bottom:1px solid #dbe2d5">${esc(state.title)}</div>${state.blocks.map(b=>b.type==='fold'?`<details id="${prefix+b.id}" style="margin:18px 0;scroll-margin-top:24px"><summary style="cursor:pointer;text-align:center;padding:12px;border-radius:8px;background:#e3e9dc;color:#617253;font-size:12px">${esc(b.label)}</summary>${b.children.map(bubble).join('')}</details>`:bubble(b)).join('')}</div>`;
}
function locationOf(id){for(const b of state.blocks){if(b.id===id)return {array:state.blocks,index:state.blocks.indexOf(b)};if(b.type==='fold'){const i=b.children.findIndex(m=>m.id===id);if(i>=0)return {array:b.children,index:i};}}return null;}
function clean(){state.blocks=state.blocks.filter(b=>b.type!=='fold'||b.children.length);}
function openMessage(id=null,after=null){editing=id;insertion=after;const m=messages().find(x=>x.id===id);$('message-person').innerHTML=state.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('message-person').value=m?.person||activePerson;$('message-text').value=m?.text||'';$('message-time').value=m?.time||'';$('message-date').value=m?.date||'';$('reply-kind').value=m?.reply?.kind||'none';$('reply-target').innerHTML=messages().filter(x=>x.id!==id).map(x=>`<option value="${x.id}">${esc(person(x.person).name)}: ${esc(x.text.slice(0,65))}</option>`).join('');if(m?.reply?.kind==='local')$('reply-target').value=m.reply.id;$('external-url').value=m?.reply?.url||'';$('external-name').value=m?.reply?.name||'';$('external-quote').value=m?.reply?.text||'';$('backlinks').value=m?.links.map(l=>l.label+' | '+l.url).join('\n')||'';replyFields();$('message-dialog').showModal();}
function replyFields(){$('local-fields').hidden=$('reply-kind').value!=='local';$('external-fields').hidden=$('reply-kind').value!=='external';}
function removeMessages(ids){const used=messages().some(m=>!ids.has(m.id)&&m.reply?.kind==='local'&&ids.has(m.reply.id));if(!confirm(used?'이 대화를 인용한 답장이 있습니다. 삭제하면 해당 답장 연결도 해제됩니다. 삭제할까요?':'선택한 대화를 삭제할까요?'))return;checkpoint();state.blocks=state.blocks.filter(b=>!ids.has(b.id));for(const b of state.blocks)if(b.type==='fold')b.children=b.children.filter(m=>!ids.has(m.id));for(const m of messages())if(m.reply?.kind==='local'&&ids.has(m.reply.id))m.reply=null;clean();selected.clear();commit();}
async function copy(text){try{await navigator.clipboard.writeText(text);notice('복사했습니다.');return true;}catch{notice('클립보드 접근이 제한되었습니다. 내보내기 창에서 직접 복사하세요.');return false;}}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('people').onclick=e=>{const b=e.target.closest('[data-person]');if(b){activePerson=b.dataset.person;renderPeople();}};
$('person-search').oninput=renderPeople;
$('person-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('photo')&&!safeUrl(f.get('photo')))return alert('프사는 http 또는 https 이미지 주소를 입력하세요.');checkpoint();Object.assign(person(activePerson),Object.fromEntries(f));commit();};
$('person-form').onclick=e=>{if(e.target.id==='remove-person'){if(state.people.length===1||messages().some(m=>m.person===activePerson))return alert('사용 중인 인물 또는 마지막 인물은 삭제할 수 없습니다. 대화의 인물을 먼저 바꿔주세요.');checkpoint();state.people=state.people.filter(p=>p.id!==activePerson);activePerson=state.people[0].id;commit();}};
$('add-person').onclick=()=>{checkpoint();const p={id:uid(),name:'새 인물',side:'left',photo:'',nick:'#54725b',text:'#34423c',bubble:'#ffffff'};state.people.push(p);activePerson=p.id;commit();};
for(const [field,prop] of [['title','title'],['post-url','url']])$(field).onchange=()=>{if(prop==='url'&&$(field).value&&!safeUrl($(field).value))return alert('올바른 게시글 주소를 입력하세요.');checkpoint();state[prop]=$(field).value;commit();};
$('add-message').onclick=()=>openMessage();$('reply-kind').onchange=replyFields;
$('message-form').onsubmit=e=>{e.preventDefault();const kind=$('reply-kind').value;let reply=null;if(kind==='local'){if(!$('reply-target').value)return alert('답장할 원본을 선택하세요.');reply={kind,id:$('reply-target').value};}if(kind==='external'){const url=safeUrl($('external-url').value);if(!url)return alert('원본 톡의 올바른 주소를 입력하세요.');reply={kind,url,name:$('external-name').value,text:$('external-quote').value};}const links=[];for(const line of $('backlinks').value.split('\n').filter(s=>s.trim())){const at=line.indexOf('|'),label=line.slice(0,at).trim(),url=safeUrl(line.slice(at+1).trim());if(at<1||!url)return alert('돌아가기 링크는 제목 | https://주소 형식으로 입력하세요.');links.push({label,url});}checkpoint();const m={id:editing||uid(),type:'message',person:$('message-person').value,text:$('message-text').value,time:$('message-time').value,date:$('message-date').value,reply,links};if(editing){const loc=locationOf(editing);loc.array[loc.index]=m;}else if(insertion){const loc=locationOf(insertion);loc.array.splice(loc.index+1,0,m);}else state.blocks.push(m);$('message-dialog').close();commit();};
$('messages').onchange=e=>{if(e.target.dataset.select){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);}if(e.target.dataset.foldLabel){checkpoint();state.blocks.find(b=>b.id===e.target.dataset.foldLabel).label=e.target.value||'··· 중략 ··· 펼치기';commit();}};
$('messages').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id}=b.dataset;if(action==='edit')return openMessage(id);if(action==='insert')return openMessage(null,id);if(action==='delete')return removeMessages(new Set([id]));if(action==='link'){if(!safeUrl(state.url))return alert('이 글의 게시 주소를 먼저 입력하세요.');const u=new URL(state.url);u.hash=targetId(id);const text=u.href;if(!await copy(text))prompt('메시지 링크를 복사하세요.',text);return;}const loc=locationOf(id);if(action==='unfold'){checkpoint();loc.array.splice(loc.index,1,...loc.array[loc.index].children);commit();}if(action==='up'||action==='down'){const next=loc.index+(action==='up'?-1:1);if(next<0||next>=loc.array.length)return;checkpoint();[loc.array[loc.index],loc.array[next]]=[loc.array[next],loc.array[loc.index]];commit();}};
$('fold').onclick=()=>{const indexes=state.blocks.map((b,i)=>selected.has(b.id)&&b.type==='message'?i:-1).filter(i=>i>=0);if(!indexes.length||indexes.length!==selected.size||indexes.at(-1)-indexes[0]+1!==indexes.length)return alert('접기 밖의 연속된 대화를 선택하세요. 중첩 접기는 지원하지 않습니다.');checkpoint();const children=state.blocks.splice(indexes[0],indexes.length);state.blocks.splice(indexes[0],0,{id:uid(),type:'fold',label:'··· 중략 ··· 펼치기',children});selected.clear();commit();};
$('delete-selected').onclick=()=>{if(selected.size)removeMessages(new Set(selected));};
$('undo').onclick=()=>{if(history.length){state=JSON.parse(history.pop());selected.clear();commit();}};
$('save').onclick=()=>download('talk-excerpt-project.json',JSON.stringify(state,null,2),'application/json');
$('load').onclick=()=>$('project-file').click();$('project-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const incoming=validate(JSON.parse(await file.text()));if(!confirm('현재 편집 내용을 불러온 프로젝트로 교체할까요?'))return;checkpoint();state=incoming;selected.clear();activePerson=state.people[0].id;commit();notice('프로젝트를 불러왔습니다.');}catch(err){alert('파일을 열 수 없습니다: '+err.message);}finally{e.target.value='';}};
$('export').onclick=()=>{$('html-output').value=output();$('export-warnings').textContent='접기 안의 원문은 구간 상단으로 연결됩니다. 다른 글의 돌아가기 링크는 양쪽 글에서 각각 갱신해야 합니다. 프사는 외부에서 접근할 수 있는 이미지 주소가 필요합니다.';$('export-dialog').showModal();};
$('copy-html').onclick=async()=>{if(await copy($('html-output').value))$('copy-html').textContent='복사 완료';else{$('html-output').focus();$('html-output').select();}};
$('download-html').onclick=()=>download('talk-excerpt.html','<!doctype html><html lang="ko"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(state.title)+'</title>'+output()+'</html>','text/html');
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
render();if(initialNotice)notice(initialNotice);
